<a href="https://colab.research.google.com/github/enthusiastic2003/Globe_ce_exploit/blob/master/debug_german.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
irisdf = pd.read_csv('./datasets/german.data', sep=' ', header=None)

In [2]:
irisdf

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A14,12,A32,A42,1736,A61,A74,3,A92,A101,...,A121,31,A143,A152,1,A172,1,A191,A201,1
996,A11,30,A32,A41,3857,A61,A73,4,A91,A101,...,A122,40,A143,A152,1,A174,1,A192,A201,1
997,A14,12,A32,A43,804,A61,A75,4,A93,A101,...,A123,38,A143,A152,1,A173,1,A191,A201,1
998,A11,45,A32,A43,1845,A61,A73,4,A93,A101,...,A124,23,A143,A153,1,A173,1,A192,A201,2
999,A12,45,A34,A41,4576,A62,A71,3,A93,A101,...,A123,27,A143,A152,1,A173,1,A191,A201,1

In [3]:
cols = ['Existing-Account-Status', 'Month-Duration', 'Credit-History', 'Purpose', 'Credit-Amount', 'Savings-Account', 'Present-Employment', 'Installment-Rate', 'Sex', 'Guarantors', 'Residence', 'Property', 'Age', 'Installment', 'Housing', 'Existing-Credits', 'Job', 'Num-People', 'Telephone', 'Foreign-Worker','Status']

In [4]:
print(len(cols))

21

In [5]:
irisdf.columns = cols

In [6]:
irisdf

,Existing-Account-Status,Month-Duration,Credit-History,Purpose,Credit-Amount,Savings-Account,Present-Employment,Installment-Rate,Sex,Guarantors,...,Property,Age,Installment,Housing,Existing-Credits,Job,Num-People,Telephone,Foreign-Worker,Status
0,A11,6,A34,A43,1169,A65,A75,4,A93,A101,...,A121,67,A143,A152,2,A173,1,A192,A201,1
1,A12,48,A32,A43,5951,A61,A73,2,A92,A101,...,A121,22,A143,A152,1,A173,1,A191,A201,2
2,A14,12,A34,A46,2096,A61,A74,2,A93,A101,...,A121,49,A143,A152,1,A172,2,A191,A201,1
3,A11,42,A32,A42,7882,A61,A74,2,A93,A103,...,A122,45,A143,A153,1,A173,2,A191,A201,1
4,A11,24,A33,A40,4870,A61,A73,3,A93,A101,...,A124,53,A143,A153,2,A173,2,A191,A201,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,A14,12,A32,A42,1736,A61,A74,3,A92,A101,...,A121,31,A143,A152,1,A172,1,A191,A201,1
996,A11,30,A32,A41,3857,A61,A73,4,A91,A101,...,A122,40,A143,A152,1,A174,1,A192,A201,1
997,A14,12,A32,A43,804,A61,A75,4,A93,A101,...,A123,38,A143,A152,1,A173,1,A191,A201,1
998,A11,45,A32,A43,1845,A61,A73,4,A93,A101,...,A124,23,A143,A153,1,A173,1,A192,A201,2
999,A12,45,A34,A41,4576,A62,A71,3,A93,A101,...,A123,27,A143,A152,1,A173,1,A191,A201,1

In [7]:
for col in irisdf.columns:
    # if the col is numeric add the column name to a list
    if irisdf[col].dtype == 'int64':
        print(col)

Month-Duration
Credit-Amount
Installment-Rate
Residence
Age
Existing-Credits
Num-People
Status

In [8]:
print(irisdf['Existing-Credits'].unique())

[2 1 3 4]

In [9]:
irisdf['Existing-Credits'].unique()

array([2, 1, 3, 4])

In [10]:
to_bin_conti = ['Month-Duration', 'Credit-Amount', 'Age']
to_bin_cat = ['Installment-Rate', 'Existing-Credits', 'Num-People', 'Residence']

In [11]:
from datasets import dataset_loader
from models import performance

In [12]:
bold = lambda x: '\033[1m' + x + '\033[0m'
name = 'german_credit'
dropped_features = []
# drop continuous features with:
# dataset_loader().continuous_features[dataset]
dataset = dataset_loader(name, dropped_features=dropped_features, n_bins=None)
print(bold('{} Dataset:'.format(name.replace('_', ' ').title())))
dataset.data

German Credit Dataset:

/home/club/Globe_ce_exploit-master/datasets.py:149: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  data = pd.read_csv(file_address, header = None, delim_whitespace = True)

,Existing-Account-Status = A11,Existing-Account-Status = A12,Existing-Account-Status = A13,Existing-Account-Status = A14,Month-Duration,Credit-History = A30,Credit-History = A31,Credit-History = A32,Credit-History = A33,Credit-History = A34,...,Job = A172,Job = A173,Job = A174,Num-People = 1,Num-People = 2,Telephone = A191,Telephone = A192,Foreign-Worker = A201,Foreign-Worker = A202,Status
0,True,False,False,False,6,False,False,False,False,True,...,False,True,False,True,False,False,True,True,False,1
1,False,True,False,False,48,False,False,True,False,False,...,False,True,False,True,False,True,False,True,False,0
2,False,False,False,True,12,False,False,False,False,True,...,True,False,False,False,True,True,False,True,False,1
3,True,False,False,False,42,False,False,True,False,False,...,False,True,False,False,True,True,False,True,False,1
4,True,False,False,False,24,False,False,False,True,False,...,False,True,False,False,True,True,False,True,False,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,True,12,False,False,True,False,False,...,True,False,False,True,False,True,False,True,False,1
996,True,False,False,False,30,False,False,True,False,False,...,False,False,True,True,False,False,True,True,False,1
997,False,False,False,True,12,False,False,True,False,False,...,False,True,False,True,False,True,False,True,False,1
998,True,False,False,False,45,False,False,True,False,False,...,False,True,False,True,False,False,True,True,False,0
999,False,True,False,False,45,False,False,False,False,True,...,False,True,False,True,False,True,False,True,False,1

In [13]:
from xgboost import XGBClassifier
from models import xgb_depths, xgb_estimators, xgb_regularizers, xgb_learning_rates, xgb_colsamples

x_train, y_train, x_test, y_test, x_means, x_stds =\
dataset.get_split(normalise=False, shuffle=False,  # do not shuffle, important for repeatability
                  return_mean_std=True, print_outputs=True)

# alternatively compute best params per dataset using grid search (below)
gamma, reg_alpha, reg_lambda = xgb_regularizers[name]
best_params = {'max_depth': xgb_depths[name], 'n_estimators': xgb_estimators[name],
               'gamma': gamma, 'reg_alpha': reg_alpha, 'reg_lambda': reg_lambda,
               'learning_rate': xgb_learning_rates[name], 'colsample_bytree': xgb_colsamples[name]}

Proportion of 1s in Training Data: 70.12%
Proportion of 1s in Test Data: 69.5%
800

In [14]:
print(bold("Dataset:") + " {}\n".format(name.replace('_', ' ').title()))

B = XGBClassifier(**best_params)
B.fit(x_train, y_train)
B_name = 'xgb'
#performance(B, x_train, x_test, y_train, y_test, normalise=None)  # no normalisation in xgb
normalise = None

norm = False if normalise is None else True
print("\n\033[1mNormalise:\033[0m {}".format(norm))
x_aff_size = (1-B.predict(x_train)).sum()
x_size = x_train.shape[0]
y_aff_size = (1-y_train).astype(int).sum()
print("\033[1mDNN Negative Predictions (Train):\033[0m {}% ({} Inputs out of {})"\
      .format(round(x_aff_size/x_size*100, 2), x_aff_size, x_size))
print("\033[1mData Negative Predictions (Train):\033[0m {}% ({} Inputs out of {})"\
      .format(round(y_aff_size/x_size*100, 2), y_aff_size, x_size))

Dataset: German Credit


Normalise: False
DNN Negative Predictions (Train): 25.5% (204 Inputs out of 800)
Data Negative Predictions (Train): 29.88% (239 Inputs out of 800)

In [15]:
for cols in to_bin_conti:
    maximum=irisdf[cols].max()
    minimum=irisdf[cols].min()
    roomRange= maximum - minimum
    print(cols+'-range:', roomRange)
    width = int(roomRange/20)
    intervals = [i for i in range(minimum,maximum + width,width)]
    print(cols+'-intervals:', intervals)
    irisdf[cols+'-bin'] = pd.cut(x=irisdf[cols], bins=intervals,
    include_lowest=True)

Month-Duration-range: 68
Month-Duration-intervals: [4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58, 61, 64, 67, 70, 73]
Credit-Amount-range: 18174
Credit-Amount-intervals: [250, 1158, 2066, 2974, 3882, 4790, 5698, 6606, 7514, 8422, 9330, 10238, 11146, 12054, 12962, 13870, 14778, 15686, 16594, 17502, 18410, 19318]
Age-range: 56
Age-intervals: [19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75]

In [16]:
for cols in to_bin_conti:
    irisdf.drop(cols, axis=1, inplace=True)

In [17]:
B.predict(x_test).shape

(200,)

In [18]:
import numpy as np

In [19]:
totake = 200

In [20]:
x_test = x_test[:totake]

In [21]:
x_test.shape

(200, 71)

In [22]:
y_proba = B.predict_proba(x_test)[:, 1] # score of being a '1'
eps = 1e-15
y_proba = np.clip(y_proba, eps, 1 - eps)
y = y_test[:totake].astype(int)

In [23]:
training_errors = - (y * np.log(y_proba) + (1 - y) * np.log(1 - y_proba))

In [24]:
from sliceline import Slicefinder

sf = Slicefinder(
    alpha = 0.95,
    k = 3,
    max_l = 3,
    min_sup = 1,
    verbose = True
)

sf.fit(x_test, training_errors)

DEBUG:sliceline.slicefinder:Dropping 0/397 features below min_sup = 1.
DEBUG:sliceline.slicefinder:Initial top-K: count=3, max=0.207209, min=0.119120
DEBUG:sliceline.slicefinder:Level 2:
DEBUG:sliceline.slicefinder: -- generated paired slice candidates: 397 -> 4790
/home/club/miniconda3/envs/tf-gpu/lib/python3.11/site-packages/sliceline/slicefinder.py:366: RuntimeWarning: invalid value encountered in divide
  (slice_errors / slice_sizes) / self.average_error_ - 1
/home/club/miniconda3/envs/tf-gpu/lib/python3.11/site-packages/sliceline/slicefinder.py:367: RuntimeWarning: divide by zero encountered in divide
  ) - (1 - self.alpha) * (n_row_x_encoded / slice_sizes - 1)
DEBUG:sliceline.slicefinder: -- valid slices after eval: 4764/4790
DEBUG:sliceline.slicefinder: -- top-K: count=3, max=0.339301, min=0.270208
DEBUG:sliceline.slicefinder:Level 3:
DEBUG:sliceline.slicefinder: -- generated paired slice candidates: 4764 -> 100093
DEBUG:sliceline.slicefinder: -- valid slices after eval: 100091/100093
DEBUG:sliceline.slicefinder: -- top-K: count=3, max=0.521320, min=0.489968
DEBUG:sliceline.slicefinder:Terminated at level 3.

Slicefinder(alpha=0.95, k=3, max_l=3, min_sup=1)

In [30]:
list(dataset.data.columns)

['Existing-Account-Status = A11',
 'Existing-Account-Status = A12',
 'Existing-Account-Status = A13',
 'Existing-Account-Status = A14',
 'Month-Duration',
 'Credit-History = A30',
 'Credit-History = A31',
 'Credit-History = A32',
 'Credit-History = A33',
 'Credit-History = A34',
 'Purpose = A40',
 'Purpose = A41',
 'Purpose = A410',
 'Purpose = A42',
 'Purpose = A43',
 'Purpose = A44',
 'Purpose = A45',
 'Purpose = A46',
 'Purpose = A48',
 'Purpose = A49',
 'Credit-Amount',
 'Savings-Account = A61',
 'Savings-Account = A62',
 'Savings-Account = A63',
 'Savings-Account = A64',
 'Savings-Account = A65',
 'Present-Employment = A71',
 'Present-Employment = A72',
 'Present-Employment = A73',
 'Present-Employment = A74',
 'Present-Employment = A75',
 'Instalment-Rate = 1',
 'Instalment-Rate = 2',
 'Instalment-Rate = 3',
 'Instalment-Rate = 4',
 'Sex = A91',
 'Sex = A92',
 'Sex = A93',
 'Sex = A94',
 'Guarantors = A101',
 'Guarantors = A102',
 'Guarantors = A103',
 'Residence = 1',
 'Residence = 2',
 'Residence = 3',
 'Residence = 4',
 'Property = A121',
 'Property = A122',
 'Property = A123',
 'Property = A124',
 'Age',
 'Installment = A141',
 'Installment = A142',
 'Installment = A143',
 'Housing = A151',
 'Housing = A152',
 'Housing = A153',
 'Existing-Credits = 1',
 'Existing-Credits = 2',
 'Existing-Credits = 3',
 'Existing-Credits = 4',
 'Job = A171',
 'Job = A172',
 'Job = A173',
 'Job = A174',
 'Num-People = 1',
 'Num-People = 2',
 'Telephone = A191',
 'Telephone = A192',
 'Foreign-Worker = A201',
 'Foreign-Worker = A202',
 'Status']

In [33]:
Scores = pd.DataFrame(sf.top_slices_, columns=list(dataset.data.columns)[:-1], index=sf.get_feature_names_out())

In [34]:
sf.top_slices_statistics_

[{'slice_score': 0.5213202512116726,
  'sum_slice_error': 12.454447388648987,
  'max_slice_error': 3.3983752727508545,
  'slice_size': 10.0,
  'slice_average_error': 1.2454447388648986},
 {'slice_score': 0.5108942308404192,
  'sum_slice_error': 12.40081948786974,
  'max_slice_error': 3.3983752727508545,
  'slice_size': 10.0,
  'slice_average_error': 1.2400819487869739},
 {'slice_score': 0.48996781476862483,
  'sum_slice_error': 10.863276839256287,
  'max_slice_error': 3.3983752727508545,
  'slice_size': 8.0,
  'slice_average_error': 1.3579096049070358}]

In [36]:
sets = []
for index,rows in Scores.iterrows():
    item = {}
    for cols in Scores.columns:
        if(rows[cols]!=None):
            item[cols] = rows[cols]
    sets.append(item)

In [37]:
sets

[{'Month-Duration': 24,
  'Savings-Account = A65': False,
  'Property = A123': True},
 {'Month-Duration': 24, 'Purpose = A49': False, 'Property = A123': True},
 {'Month-Duration': 24,
  'Present-Employment = A74': False,
  'Property = A123': True}]